name       : xbacklight
version    : 1.2.3
release    : 4
source     :
    - https://www.x.org/releases/individual/app/xbacklight-1.2.3.tar.gz : d2a8dd962454d8de3675286eab4edc4d1376ac7da040a3a8729ee250e6e798c1
license    : MIT
component  : xorg.apps
summary    : RandR-based backlight control application
description: |
    RandR-based backlight control application
builddeps  :
    - pkgconfig(xcb-util)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
