name       : xbacklight
version    : 1.2.1
release    : 2
source     :
    - https://www.x.org/archive/individual/app/xbacklight-1.2.1.tar.gz : 82c80cd851e3eb6d7a216d92465fcf6d5e456c2d5ac12c63cd2757b39fb65b10
license    : MIT
component  : xorg.apps
summary    : RandR-based backlight control application
description: |
    RandR-based backlight control application
builddeps  :
    - pkgconfig(xcb-util)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
