name       : xbacklight
version    : 1.2.2
release    : 3
source     :
    - https://www.x.org/releases/individual/app/xbacklight-1.2.2.tar.gz : 9812497b95b28776539808ba75e8b8a2d48a57416e172e04e9580e65c76a61bb
license    : MIT
component  : xorg.apps
summary    : RandR-based backlight control application
description: |
    RandR-based backlight control application
builddeps  :
    - pkgconfig(xcb-util)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
